export {default as Main} from './Main/Main'
export {default as Notes} from './ToDoApp/Notes'
export {default as financePortfolio} from './FinancePortfolio/FinancePortfolio'
export {default as Settings} from './Settings/Settings'
export {default as Sidebar} from './Sidebar/Sidebar'
export {default as Login} from './Auth/Login/Login'
export {default as Register} from './Auth/Register/Register'